import { Announcement, BoardMessage, Person } from "./types";

const gradients = [
  "from-westmont-navy to-westmont-sky",
  "from-westmont-blue to-westmont-gold",
  "from-indigo-600 to-purple-500",
  "from-emerald-600 to-teal-400",
  "from-rose-600 to-orange-400",
  "from-cyan-600 to-blue-500",
  "from-amber-600 to-yellow-400",
  "from-fuchsia-600 to-pink-400",
];

const g = (i: number) => gradients[i % gradients.length];

export const alumni: Person[] = [
  {
    id: "a1",
    role: "alumni",
    name: "Maya Chen",
    email: "maya.chen@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/mayachen",
    avatarColor: g(0),
    major: "Computer Science",
    gradYear: 2019,
    location: "San Francisco, CA",
    currentRole: "Senior Software Engineer",
    company: "Stripe",
    interests: ["Distributed Systems", "Mentoring", "Rock Climbing"],
    askMeAbout: ["Breaking into Big Tech", "System Design Interviews", "Backend Engineering"],
    bio: "CATLab alum who interned twice before landing a new-grad role. Happy to do mock interviews and resume reviews.",
  },
  {
    id: "a2",
    role: "alumni",
    name: "Jordan Whitfield",
    email: "jwhitfield@protonmail.com",
    linkedinUrl: "https://www.linkedin.com/in/jordanwhitfield",
    avatarColor: g(1),
    major: "Data Analytics",
    gradYear: 2020,
    location: "Seattle, WA",
    currentRole: "Data Scientist",
    company: "Microsoft",
    interests: ["Machine Learning", "Hiking", "Coffee Roasting"],
    askMeAbout: ["Transitioning into Data Science", "Grad School vs Industry", "SQL & Python"],
    bio: "Went from a stats class at CATLab to ML at Microsoft. Ask me about portfolio projects that actually get noticed.",
  },
  {
    id: "a3",
    role: "alumni",
    name: "Priya Raman",
    email: "priya.raman@outlook.com",
    linkedinUrl: "https://www.linkedin.com/in/priyaraman",
    avatarColor: g(2),
    major: "Engineering",
    gradYear: 2018,
    location: "Austin, TX",
    currentRole: "Product Manager",
    company: "Atlassian",
    interests: ["Product Strategy", "UX Research", "Yoga"],
    askMeAbout: ["Engineering to PM", "Product Interviews", "Roadmapping"],
    bio: "Started as an embedded engineer, pivoted to product. Love helping students figure out if PM is right for them.",
  },
  {
    id: "a4",
    role: "alumni",
    name: "Marcus Lee",
    email: "marcus.lee.dev@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/marcuslee",
    avatarColor: g(3),
    major: "Computer Science",
    gradYear: 2021,
    location: "Remote",
    currentRole: "Founding Engineer",
    company: "Lumen (YC startup)",
    interests: ["Startups", "TypeScript", "Bouldering"],
    askMeAbout: ["Joining Early-Stage Startups", "Equity & Offers", "Full-Stack Web"],
    bio: "Employee #3 at a YC company. Ask me about the startup vs. big-co tradeoff and negotiating equity.",
  },
  {
    id: "a5",
    role: "alumni",
    name: "Sofia Alvarez",
    email: "sofia.alvarez@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/sofiaalvarez",
    avatarColor: g(4),
    major: "Data Analytics",
    gradYear: 2017,
    location: "New York, NY",
    currentRole: "Engineering Manager",
    company: "Spotify",
    interests: ["Leadership", "Music Tech", "Marathon Running"],
    askMeAbout: ["Growing into Management", "Career Pacing", "Women in Tech"],
    bio: "Manage a team of 9 engineers. Passionate about helping first-gen students navigate their first few years.",
  },
  {
    id: "a6",
    role: "alumni",
    name: "Daniel Okafor",
    email: "d.okafor@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/danielokafor",
    avatarColor: g(5),
    major: "Engineering",
    gradYear: 2022,
    location: "Los Angeles, CA",
    currentRole: "Robotics Engineer",
    company: "Anduril",
    interests: ["Robotics", "C++", "Drone Photography"],
    askMeAbout: ["Hardware/Robotics Careers", "Defense Tech", "Internship Hunting"],
    bio: "If you like building things that move in the real world, let's talk. Recent grad, remember the grind well.",
  },
  {
    id: "a7",
    role: "alumni",
    name: "Hannah Kim",
    email: "hannah.kim.design@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/hannahkim",
    avatarColor: g(6),
    major: "Computer Science",
    gradYear: 2019,
    location: "San Diego, CA",
    currentRole: "Senior UX Designer",
    company: "Intuit",
    interests: ["Design Systems", "Accessibility", "Ceramics"],
    askMeAbout: ["UX/UI Career Paths", "Building a Design Portfolio", "Design + Code"],
    bio: "CS major who fell in love with design. Happy to review portfolios and talk about the design hiring process.",
  },
  {
    id: "a8",
    role: "alumni",
    name: "Tyler Brooks",
    email: "tyler.brooks@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/tylerbrooks",
    avatarColor: g(7),
    major: "Data Analytics",
    gradYear: 2016,
    location: "Denver, CO",
    currentRole: "Director of Analytics",
    company: "Salesforce",
    interests: ["Analytics Leadership", "Mentoring", "Skiing"],
    askMeAbout: ["Long-Term Career Growth", "Analytics Org Building", "Interviewing"],
    bio: "One of the earliest CATLab grads. I've hired 50+ people — ask me what makes a resume stand out.",
  },
  {
    id: "a9",
    role: "alumni",
    name: "Grace Liu",
    email: "grace.liu@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/graceliu",
    avatarColor: g(0),
    major: "Computer Science",
    gradYear: 2023,
    location: "Mountain View, CA",
    currentRole: "Software Engineer",
    company: "Google",
    interests: ["Mobile Dev", "Open Source", "Baking"],
    askMeAbout: ["New Grad Recruiting", "Big Tech Interviews", "Android Development"],
    bio: "Just went through new-grad recruiting recently — I can share exactly what worked and what didn't.",
  },
  {
    id: "a10",
    role: "alumni",
    name: "Andre Santos",
    email: "andre.santos@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/andresantos",
    avatarColor: g(1),
    major: "Engineering",
    gradYear: 2015,
    location: "Boston, MA",
    currentRole: "CTO & Co-Founder",
    company: "HealthBridge",
    interests: ["Entrepreneurship", "HealthTech", "Sailing"],
    askMeAbout: ["Starting a Company", "Fundraising", "Tech in Healthcare"],
    bio: "Founded a health-tech startup that raised a Series A. Love mentoring would-be founders.",
  },
  {
    id: "a11",
    role: "alumni",
    name: "Rachel Nguyen",
    email: "rachel.nguyen@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/rachelnguyen",
    avatarColor: g(2),
    major: "Data Analytics",
    gradYear: 2021,
    location: "Chicago, IL",
    currentRole: "Machine Learning Engineer",
    company: "Capital One",
    interests: ["MLOps", "Fairness in AI", "Volleyball"],
    askMeAbout: ["ML Engineering vs Data Science", "Finance Tech", "Cloud & MLOps"],
    bio: "Build ML systems in fintech. Happy to demystify the difference between all the 'data' job titles.",
  },
  {
    id: "a12",
    role: "alumni",
    name: "Caleb Foster",
    email: "caleb.foster@gmail.com",
    linkedinUrl: "https://www.linkedin.com/in/calebfoster",
    avatarColor: g(3),
    major: "Computer Science",
    gradYear: 2020,
    location: "Portland, OR",
    currentRole: "Security Engineer",
    company: "Cloudflare",
    interests: ["Cybersecurity", "CTFs", "Mountain Biking"],
    askMeAbout: ["Getting into Security", "CTFs & Certs", "Networking Fundamentals"],
    bio: "Turned a hobby of CTF competitions into a security career. Ask me how to start with zero experience.",
  },
];

export const students: Person[] = [
  {
    id: "s1",
    role: "student",
    name: "Emma Thompson",
    email: "ethompson@westmont.edu",
    linkedinUrl: "https://www.linkedin.com/in/emmathompson",
    avatarColor: g(4),
    major: "Computer Science",
    gradYear: 2027,
    expectedGradYear: 2027,
    location: "Santa Barbara, CA",
    interests: ["Web Development", "AI", "Photography"],
    lookingFor: ["Summer Internships", "Resume Feedback", "Big Tech Advice"],
    bio: "Sophomore building my first side projects. Looking to land a summer internship and learn from people who've done it.",
  },
  {
    id: "s2",
    role: "student",
    name: "Noah Patel",
    email: "npatel@westmont.edu",
    linkedinUrl: "https://www.linkedin.com/in/noahpatel",
    avatarColor: g(5),
    major: "Data Analytics",
    gradYear: 2026,
    expectedGradYear: 2026,
    location: "Santa Barbara, CA",
    interests: ["Data Science", "Sports Analytics", "Basketball"],
    lookingFor: ["Data Science Mentorship", "Portfolio Project Ideas", "Grad School Advice"],
    bio: "Junior obsessed with sports analytics. Trying to decide between industry and a master's program.",
  },
  {
    id: "s3",
    role: "student",
    name: "Olivia Martinez",
    email: "omartinez@westmont.edu",
    linkedinUrl: "https://www.linkedin.com/in/oliviamartinez",
    avatarColor: g(6),
    major: "Engineering",
    gradYear: 2025,
    expectedGradYear: 2025,
    location: "Santa Barbara, CA",
    interests: ["Robotics", "Embedded Systems", "Rock Climbing"],
    lookingFor: ["Full-Time Job Leads", "Hardware Career Advice", "Interview Prep"],
    bio: "Senior graduating this year. Looking for full-time hardware/robotics roles and people to do mock interviews with.",
  },
  {
    id: "s4",
    role: "student",
    name: "Liam Johnson",
    email: "ljohnson@westmont.edu",
    avatarColor: g(7),
    major: "Computer Science",
    gradYear: 2028,
    expectedGradYear: 2028,
    location: "Santa Barbara, CA",
    interests: ["Game Development", "C#", "Music Production"],
    lookingFor: ["First Internship", "Where to Start", "Project Feedback"],
    bio: "First-year still figuring things out. Curious about all the different paths a CS degree can take.",
  },
  {
    id: "s5",
    role: "student",
    name: "Ava Robinson",
    email: "arobinson@westmont.edu",
    linkedinUrl: "https://www.linkedin.com/in/avarobinson",
    avatarColor: g(0),
    major: "Data Analytics",
    gradYear: 2026,
    expectedGradYear: 2026,
    location: "Santa Barbara, CA",
    interests: ["Product", "UX Research", "Painting"],
    lookingFor: ["PM Career Advice", "Internships", "Networking Tips"],
    bio: "Junior interested in the intersection of data and product. Would love to talk to anyone in PM or UX.",
  },
  {
    id: "s6",
    role: "student",
    name: "Ethan Garcia",
    email: "egarcia@westmont.edu",
    linkedinUrl: "https://www.linkedin.com/in/ethangarcia",
    avatarColor: g(1),
    major: "Computer Science",
    gradYear: 2025,
    expectedGradYear: 2025,
    location: "Santa Barbara, CA",
    interests: ["Startups", "Full-Stack", "Surfing"],
    lookingFor: ["Startup Connections", "Equity Questions", "Job Referrals"],
    bio: "Senior who wants to join an early-stage startup. Looking for founders and early employees to learn from.",
  },
  {
    id: "s7",
    role: "student",
    name: "Sophia Wright",
    email: "swright@westmont.edu",
    avatarColor: g(2),
    major: "Engineering",
    gradYear: 2027,
    expectedGradYear: 2027,
    location: "Santa Barbara, CA",
    interests: ["Sustainability", "CAD", "Hiking"],
    lookingFor: ["Internships", "Cleantech Advice", "Resume Help"],
    bio: "Sophomore passionate about clean energy. Looking for internships and anyone working in sustainability/cleantech.",
  },
  {
    id: "s8",
    role: "student",
    name: "Mason Davis",
    email: "mdavis@westmont.edu",
    linkedinUrl: "https://www.linkedin.com/in/masondavis",
    avatarColor: g(3),
    major: "Data Analytics",
    gradYear: 2025,
    expectedGradYear: 2025,
    location: "Santa Barbara, CA",
    interests: ["Machine Learning", "Finance", "Chess"],
    lookingFor: ["ML/Quant Roles", "Interview Prep", "Grad School vs Industry"],
    bio: "Senior weighing quant finance vs. ML engineering. Would value advice from anyone in either field.",
  },
];

export const people: Person[] = [...alumni, ...students];

export function getPerson(id: string): Person | undefined {
  return people.find((p) => p.id === id);
}

export const announcements: Announcement[] = [
  {
    id: "an1",
    title: "Welcome to the CATLab Network! 🎉",
    body: "This is the new home for connecting CATLab students with our incredible alumni community. Fill out your profile, browse the directory, and reach out — that's what this is for. Questions? Find the Creative Team on the message board.",
    author: "CATLab Creative Team",
    date: "2026-06-10T09:00:00Z",
    pinned: true,
  },
  {
    id: "an2",
    title: "Summer Mentorship Program — Sign-ups Open",
    body: "We're pairing students with alumni mentors for the summer. Browse the Alumni tab, find someone whose path excites you, and reach out directly. Aiming for first meetings by the end of June.",
    author: "CATLab Creative Team",
    date: "2026-06-12T15:30:00Z",
    pinned: true,
  },
  {
    id: "an3",
    title: "Alumni Spotlight: Andre Santos ('15)",
    body: "Andre went from an Engineering degree to founding HealthBridge, a Series-A health-tech startup in Boston. He's joined the network and is open to chatting with aspiring founders. Check out his card in the Alumni tab!",
    author: "CATLab Creative Team",
    date: "2026-06-14T12:00:00Z",
  },
];

export const seedMessages: BoardMessage[] = [
  {
    id: "m1",
    author: "Maya Chen",
    role: "alumni",
    category: "Job",
    body: "Stripe is hiring new-grad backend engineers for Fall 2026! Remote-friendly. Happy to refer CATLab folks — reach out via my card before you apply.",
    date: "2026-06-13T18:20:00Z",
  },
  {
    id: "m2",
    author: "CATLab Creative Team",
    role: "staff",
    category: "Event",
    body: "Virtual alumni panel on 'Breaking into Tech' — Friday June 26 at 5pm PT. Maya, Grace, and Daniel will be answering questions. Zoom link to follow.",
    date: "2026-06-13T20:00:00Z",
  },
  {
    id: "m3",
    author: "Sofia Alvarez",
    role: "alumni",
    category: "Internship",
    body: "Spotify NYC has a couple of analytics internship spots opening up for next summer. DM me through my profile if you want details on the application.",
    date: "2026-06-14T16:45:00Z",
  },
  {
    id: "m4",
    author: "Noah Patel",
    role: "student",
    category: "General",
    body: "Anyone done a sports-analytics project they're proud of? Looking for inspiration / a portfolio idea before internship season. 🙏",
    date: "2026-06-15T01:10:00Z",
  },
];
